// Pairing: ZedraPairingTicket encoding and HMAC helpers.
//
// The QR code payload is `zedra://<ticket>` where `<ticket>` is
// `"zedra" + BASE32LOWER(postcard(ZedraPairingTicket))`.
//
// The old encode_endpoint_addr / decode_endpoint_addr are kept for use
// in the QR display helpers that show raw endpoint info.

use anyhow::Result;
use data_encoding::BASE32_NOPAD;
use hmac::{Hmac, Mac};
use serde::{Deserialize, Serialize};
use sha2::Sha256;

type HmacSha256 = Hmac<Sha256>;

// ---------------------------------------------------------------------------
// ZedraPairingTicket
// ---------------------------------------------------------------------------

/// QR code payload.
///
/// Contains the host's EndpointId (for pkarr resolution) and a one-use
/// handshake key for initial client registration. Routing info is not
/// embedded — it is resolved dynamically via pkarr at connect time.
///
/// String form: `"zedra" + BASE32LOWER(postcard(self))`
/// QR URL form: `"zedra://" + string_form`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ZedraPairingTicket {
    /// Host's 32-byte Ed25519 public key.
    /// Used as pkarr lookup key and to verify AuthChallenge signatures.
    pub endpoint_id: iroh::PublicKey,
    /// 32-byte random key generated by the host for this pairing slot.
    /// One-use: consumed on first valid RegisterClient message.
    /// Client uses this as HMAC key to prove QR was scanned, not guessed.
    pub handshake_key: [u8; 32],
    /// The session this QR was generated for.
    /// New client's pubkey is auto-added to this session's ACL on Register.
    pub session_id: String,
}

const TICKET_PREFIX: &str = "zedra";

impl ZedraPairingTicket {
    /// Encode to `"zedra<BASE32LOWER>"` string.
    pub fn encode(&self) -> Result<String> {
        let bytes = postcard::to_allocvec(self)?;
        let b32 = BASE32_NOPAD.encode(&bytes).to_lowercase();
        Ok(format!("{}{}", TICKET_PREFIX, b32))
    }

    /// Decode from `"zedra<BASE32LOWER>"` string.
    pub fn decode(s: &str) -> Result<Self> {
        let rest = s
            .strip_prefix(TICKET_PREFIX)
            .ok_or_else(|| anyhow::anyhow!("missing 'zedra' prefix in ticket"))?;
        let bytes = BASE32_NOPAD
            .decode(rest.to_uppercase().as_bytes())
            .map_err(|e| anyhow::anyhow!("invalid base32 in ticket: {}", e))?;
        let ticket: Self = postcard::from_bytes(&bytes)?;
        Ok(ticket)
    }

    /// Encode to a `zedra://` QR URL.
    pub fn to_qr_url(&self) -> Result<String> {
        Ok(format!("zedra://{}", self.encode()?))
    }

    /// Decode from a `zedra://` QR URL (or bare ticket string).
    pub fn from_qr_url(url: &str) -> Result<Self> {
        let s = url.strip_prefix("zedra://").unwrap_or(url);
        Self::decode(s)
    }
}

// ---------------------------------------------------------------------------
// Registration HMAC
// ---------------------------------------------------------------------------

/// Compute HMAC-SHA256 used in RegisterClient.
///
/// `HMAC-SHA256(handshake_key, client_pubkey || timestamp_le_bytes)`
///
/// Proves the sender physically scanned the QR (has the handshake_key).
/// The timestamp prevents replay of a captured packet.
pub fn compute_registration_hmac(
    handshake_key: &[u8; 32],
    client_pubkey: &[u8; 32],
    timestamp: u64,
) -> [u8; 32] {
    let mut mac =
        HmacSha256::new_from_slice(handshake_key).expect("HMAC accepts any key size");
    mac.update(client_pubkey);
    mac.update(&timestamp.to_le_bytes());
    let result = mac.finalize().into_bytes();
    let mut out = [0u8; 32];
    out.copy_from_slice(&result);
    out
}

/// Verify a registration HMAC in constant time.
///
/// Returns `true` if the HMAC is valid.
pub fn verify_registration_hmac(
    handshake_key: &[u8; 32],
    client_pubkey: &[u8; 32],
    timestamp: u64,
    provided_hmac: &[u8; 32],
) -> bool {
    let mut mac =
        HmacSha256::new_from_slice(handshake_key).expect("HMAC accepts any key size");
    mac.update(client_pubkey);
    mac.update(&timestamp.to_le_bytes());
    mac.verify_slice(provided_hmac).is_ok()
}

// ---------------------------------------------------------------------------
// Legacy helpers (kept for QR display in qr.rs)
// ---------------------------------------------------------------------------

/// Encode an iroh EndpointAddr to a compact string for QR display.
pub fn encode_endpoint_addr(addr: &iroh::EndpointAddr) -> Result<String> {
    let bytes = postcard::to_allocvec(addr)?;
    Ok(base64_url::encode(&bytes))
}

/// Decode an iroh EndpointAddr from a compact string.
pub fn decode_endpoint_addr(s: &str) -> Result<iroh::EndpointAddr> {
    let bytes =
        base64_url::decode(s).map_err(|e| anyhow::anyhow!("invalid base64-url: {}", e))?;
    let addr: iroh::EndpointAddr = postcard::from_bytes(&bytes)?;
    Ok(addr)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn test_key() -> iroh::SecretKey {
        iroh::SecretKey::from([42u8; 32])
    }

    #[test]
    fn ticket_roundtrip() {
        let ticket = ZedraPairingTicket {
            endpoint_id: test_key().public(),
            handshake_key: [7u8; 32],
            session_id: "test-session-id".to_string(),
        };

        let encoded = ticket.encode().unwrap();
        assert!(encoded.starts_with("zedra"), "encoded: {}", encoded);

        let decoded = ZedraPairingTicket::decode(&encoded).unwrap();
        assert_eq!(decoded, ticket);
    }

    #[test]
    fn ticket_qr_url_roundtrip() {
        let ticket = ZedraPairingTicket {
            endpoint_id: test_key().public(),
            handshake_key: [9u8; 32],
            session_id: "sess-abc".to_string(),
        };
        let url = ticket.to_qr_url().unwrap();
        assert!(url.starts_with("zedra://zedra"));
        let decoded = ZedraPairingTicket::from_qr_url(&url).unwrap();
        assert_eq!(decoded, ticket);
    }

    #[test]
    fn ticket_decode_missing_prefix_fails() {
        assert!(ZedraPairingTicket::decode("notavalidticket").is_err());
    }

    #[test]
    fn hmac_verify_correct() {
        let key = [1u8; 32];
        let pubkey = [2u8; 32];
        let ts = 1_700_000_000u64;
        let mac = compute_registration_hmac(&key, &pubkey, ts);
        assert!(verify_registration_hmac(&key, &pubkey, ts, &mac));
    }

    #[test]
    fn hmac_verify_wrong_key_fails() {
        let key = [1u8; 32];
        let wrong_key = [2u8; 32];
        let pubkey = [3u8; 32];
        let ts = 1_700_000_000u64;
        let mac = compute_registration_hmac(&key, &pubkey, ts);
        assert!(!verify_registration_hmac(&wrong_key, &pubkey, ts, &mac));
    }

    #[test]
    fn hmac_verify_wrong_timestamp_fails() {
        let key = [1u8; 32];
        let pubkey = [3u8; 32];
        let ts = 1_700_000_000u64;
        let mac = compute_registration_hmac(&key, &pubkey, ts);
        assert!(!verify_registration_hmac(&key, &pubkey, ts + 1, &mac));
    }

    #[test]
    fn endpoint_addr_roundtrip() {
        let addr = iroh::EndpointAddr::from(test_key().public());
        let encoded = encode_endpoint_addr(&addr).unwrap();
        let decoded = decode_endpoint_addr(&encoded).unwrap();
        assert_eq!(addr, decoded);
    }
}
